# Generated by Django 5.1.5 on 2025-01-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['-date'], 'verbose_name': 'Выручка', 'verbose_name_plural': 'Выручка'},
        ),
    ]
