# Generated by Django 5.1.5 on 2025-01-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
