# Generated by Django 5.1.5 on 2025-01-22 09:31

import orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[orders.validators.ValidatePrice()]),
        ),
    ]
