# Generated by Django 5.1.5 on 2025-01-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderdish_price_at_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderdish',
            options={'ordering': ['order'], 'verbose_name': 'Блюдо в заказе', 'verbose_name_plural': 'Блюда в заказах'},
        ),
    ]
